
name: Build on Ubuntu

on:
  pull_request:

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - run: |
        sudo apt update && sudo apt install -y shellcheck shfmt
        chmod +x lint.sh
        ./lint.sh
